---
- name: Install utils packages
  hosts: pxubuntu102
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: To use ausyscall (to know the number for syscall)
      apt:
        name:
        - auditd

        state: present
